# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-byte-order-marker # Forbid UTF-8 byte-order markers
      - id: check-case-conflict      # Check for case conflicts on filesystems
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: \.xml$
      - id: trailing-whitespace
        exclude: \.xml$
      - id: mixed-line-ending
      - id: debug-statements
      - id: check-added-large-files
        exclude: 'web/com.etendoerp.copilot.dist/assets/index-.*\.js'
  - repo: https://github.com/pycqa/pydocstyle
    rev: "6.3.0"
    hooks:
      - id: pydocstyle
        args:
          [
            "--add-ignore=D100,D101,D102,D103,D104,D105,D106,D107,D205,D209,D415,D212,D417",
            "--convention=google",
          ]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.275
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: install-export-plugin
        name: Install Poetry Export Plugin
        entry: pip install poetry-plugin-export
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: export-requirements
        name: Export requirements.txt from poetry.lock
        entry: poetry export -f requirements.txt --output requirements.txt --without-hashes
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: check-gitpolice-repo
        name: Check and Clone GitPolice Repository
        entry: bash -c '[ -d "$HOME/.gitpolice/.git" ] || git clone git@bitbucket.org:koodu_software/com.etendoerp.gitpolice.git "$HOME/.gitpolice"'
        language: system
      - id: gitpolice-update
        name: Update GitPolice Repository
        entry: bash -c 'cd "$HOME/.gitpolice" && git pull'
        language: system
  - repo: local
    hooks:
      - id: build-UI
        language: system
        name: Build UI
        entry: bash -c 'cd web/com.etendoerp.copilot.chat/ && yarn install && yarn build'
        files: ^web/com\.etendoerp\.copilot\.chat/
