[tool.poetry]
name = "prueba autogen"
version = "0.1.0"
description = ""
authors = ["Rocio Altamirano <rocio.altamirano@smfconsulting.es>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
 