services:
  copilot:
    image: etendo/etendo_copilot_slim:${COPILOT_IMAGE_TAG}
    ports:
      - "${COPILOT_PORT}:${COPILOT_PORT}"
    env_file: ".env"
    volumes:
      - ../copilot:/app/
      - ${SOURCE_PATH}/modules:/modules
      - pip_cache:/root/.cache/pip
      - copilot_attached_files:/copilotAttachedFiles
      - vectordbs:/app/vectordbs
    networks:
      - etendo
volumes:
  pip_cache:
  copilot_attached_files:
  vectordbs:

