services:
  copilot:
    image: etendo/etendo_copilot_slim:${COPILOT_IMAGE_TAG}
    ports:
      - "${COPILOT_PORT}:${COPILOT_PORT}"
      - "${COPILOT_PORT_DEBUG}:${COPILOT_PORT_DEBUG}"
    env_file: ".env"
    volumes:
      - ../copilot:/app/
      - ${SOURCE_PATH}/modules:/modules
      - pip_cache:/root/.cache/pip
      - copilot_attached_files:/copilotAttachedFiles
      - vectordbs:/app/vectordbs
      - checkpoints:/checkpoints
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - etendo
volumes:
  pip_cache:
  copilot_attached_files:
  vectordbs:
  checkpoints:
