services:
  copilot:
    build:
      context: ../copilot
      dockerfile: ../copilot/Dockerfile
    ports:
      - "${COPILOT_PORT}:${COPILOT_PORT}"
      - "${COPILOT_PORT_DEBUG}:${COPILOT_PORT_DEBUG}"
      - "${COPILOT_PORT_MCP}:${COPILOT_PORT_MCP}"
    env_file: ".env"
    volumes:
      - ../copilot:/app/
      - ${SOURCE_PATH}/modules:/modules
      - copilot_attached_files:/copilotAttachedFiles
      - vectordbs:/app/vectordbs
      - checkpoints:/checkpoints
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - etendo
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  copilot_attached_files:
  vectordbs:
