services:
  ollama:
    image: ollama/ollama
    ports:
      - "${COPILOT_OLLAMA_PORT}:11434"
    env_file: ".env"
    volumes:
      - ollama_models:/root/.ollama/models
    networks:
      - etendo
volumes:
  ollama_models:
