name: Docker Image Build

on:
  push:
    branches:
      - master
      - develop
      - experimental
      - 'epic/*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Determine Image Tag
        id: image_tag
        run: |
          if [[ "${{ github.ref_name }}" == "master" || \
                "${{ github.ref_name }}" == "develop" || \
                "${{ github.ref_name }}" == "experimental" ]]; then
            sanitizedBranchName=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9_-]/_/g')
            echo "branch_name=${sanitizedBranchName}" >> $GITHUB_ENV
            sanitized_branch_name=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9_-]/_/g')
            echo "branch_name=${sanitized_branch_name}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Build and push full image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: full.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: etendo/etendo_copilot_core:${{ env.branch_name }}

      - name: Build and push slim image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: slim.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: etendo/etendo_copilot_slim:${{ env.branch_name }}
