name: Validate Merge to Develop

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  validate-merge:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Fetch all branches
      - name: Fetch all branches
        run: git fetch --all

      # 3. Check if the latest commit exists in experimental
      - name: Check if last commit is in experimental branch
        run: |
          # Get the source branch of the PR
          PR_BRANCH=${{ github.head_ref }}

          # Get the hash of the last commit in the PR branch
          LAST_COMMIT=$(git rev-parse origin/$PR_BRANCH)

          # Check if the last commit exists in experimental
          if git merge-base --is-ancestor $LAST_COMMIT origin/experimental; then
            echo "The latest commit ($LAST_COMMIT) from $PR_BRANCH is already included in experimental."
          else
            echo "Error: The latest commit ($LAST_COMMIT) from $PR_BRANCH is not included in experimental."
            exit 1
          fi
